---
#
# Duplicati Backup Service
#   version 2026-02-08
#

services:
  backup:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: backup
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - backup_config:/config
      - /home/justin/backups:/backups:ro
      - mealie_mealie-data:/source/mealie:ro  # Need to sort this one out perhaps
    ports:
      - 83:8200
    restart: unless-stopped

volumes:
  backup_config:
  backup-staging:
    external: true
  mealie_mealie-data:
    external: true
