---
services:
  backup:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: backup
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='Australia/Sydney'
    volumes:
      - backup_config:/config
      - /mnt/storage/backups:/backups
    ports:
      - 83:8200
    restart: unless-stopped

volumes:
  backup_config:
